apiVersion: v1
kind: Service
metadata:
  name: fortune
spec:
  selector:
    app: fortune
  ports:
   -  protocol: TCP
      port: 8080
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortune
  labels:
    app: fortune
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fortune
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fortune
    spec:
      containers:
      - image: fortune:latest
        imagePullPolicy: Never
        name: fortune
        ports:
        - containerPort: 80
          protocol: TCP